# Generated by Django 5.0 on 2026-03-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
