# Generated by Django 5.0 on 2026-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(),
        ),
    ]
